name: Github pages storybook deploy
on:
  push:
    paths: ["/**""] # Trigger the action only when files change in the folders defined here
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false

      - name: Install and Build ğŸ”§
        run: | # Install npm packages and build the Storybook files
          npm i
          npm run storybook-build

      - name: Deploy ğŸš€
        uses: JamesIves/github-pages-deploy-action@3.6.2
        with:
          GITHUB_TOKEN: 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
          BRANCH: main # The branch the action should deploy to.
          CLEAN: true # Automatically remove deleted files from the deploy branch
